module.exports.auth = {
  master: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0eXBlIjoibWFzdGVyIiwiaWF0IjoxNTIxMjY1MTgwLCJleHAiOjQ2NzcwMjUxODAsImlzcyI6InNlcnZpci5tZSJ9.vZpBaJYg09EaXU8U3_81ETrGbDMlsdInwAb_NG3OmcY',
  admin: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0eXBlIjoiYWRtaW4iLCJpYXQiOjE1MjEyNjIyMjksImV4cCI6NDY3NzAyMjIyOSwiaXNzIjoic2VydmlyLm1lIn0.PR2GOxkw4aJoGK6hzhnatOO3_sBJW6YMj-1dzv_6MUM',
}
